# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lexiquegui.ui'
#
# Created: Thu Oct 08 18:15:13 2009
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(789, 593)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Label = QtGui.QLabel(self.centralwidget)
        self.Label.setObjectName("Label")
        self.gridLayout_3.addWidget(self.Label, 1, 1, 1, 1)
        self.Label_2 = QtGui.QLabel(self.centralwidget)
        self.Label_2.setObjectName("Label_2")
        self.gridLayout_3.addWidget(self.Label_2, 2, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.TSearch = QtGui.QTextEdit(self.centralwidget)
        self.TSearch.setEnabled(True)
        self.TSearch.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("KacstOne")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.TSearch.setFont(font)
        self.TSearch.setTabChangesFocus(False)
        self.TSearch.setUndoRedoEnabled(False)
        self.TSearch.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.TSearch.setAcceptRichText(False)
        self.TSearch.setObjectName("TSearch")
        self.gridLayout_5.addWidget(self.TSearch, 0, 0, 1, 1)
        self.CBLanguage = QtGui.QComboBox(self.centralwidget)
        self.CBLanguage.setObjectName("CBLanguage")
        self.CBLanguage.addItem(QtCore.QString())
        self.gridLayout_5.addWidget(self.CBLanguage, 0, 5, 1, 1)
        self.CBLexique = QtGui.QComboBox(self.centralwidget)
        self.CBLexique.setObjectName("CBLexique")
        self.CBLexique.addItem(QtCore.QString())
        self.CBLexique.addItem(QtCore.QString())
        self.CBLexique.addItem(QtCore.QString())
        self.gridLayout_5.addWidget(self.CBLexique, 0, 2, 1, 1)
        self.BConjugate = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("ae_AlMateen")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.BConjugate.setFont(font)
        self.BConjugate.setObjectName("BConjugate")
        self.gridLayout_5.addWidget(self.BConjugate, 0, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_5)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.TabVoice = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.TabVoice.setFont(font)
        self.TabVoice.setObjectName("TabVoice")
        self.TabResult = QtGui.QWidget()
        self.TabResult.setObjectName("TabResult")
        self.gridLayout_2 = QtGui.QGridLayout(self.TabResult)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TabActiveResult = QtGui.QTableWidget(self.TabResult)
        font = QtGui.QFont()
        font.setFamily("Traditional Arabic")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.TabActiveResult.setFont(font)
        self.TabActiveResult.setRowCount(25)
        self.TabActiveResult.setColumnCount(3)
        self.TabActiveResult.setObjectName("TabActiveResult")
        self.TabActiveResult.setColumnCount(3)
        self.TabActiveResult.setRowCount(25)
        item = QtGui.QTableWidgetItem()
        self.TabActiveResult.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.TabActiveResult.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.TabActiveResult.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.TabActiveResult, 0, 0, 1, 1)
        self.TabVoice.addTab(self.TabResult, "")
        self.gridLayout.addWidget(self.TabVoice, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_6 = QtGui.QMenu(self.menu)
        self.menu_6.setObjectName("menu_6")
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtGui.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtGui.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtGui.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.AExport = QtGui.QAction(MainWindow)
        self.AExport.setObjectName("AExport")
        self.AExit = QtGui.QAction(MainWindow)
        self.AExit.setObjectName("AExit")
        self.AFont = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ar/images/application_x_font_afm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AFont.setIcon(icon)
        self.AFont.setObjectName("AFont")
        self.AAbout = QtGui.QAction(MainWindow)
        self.AAbout.setObjectName("AAbout")
        self.AManual = QtGui.QAction(MainWindow)
        self.AManual.setObjectName("AManual")
        self.ACopy = QtGui.QAction(MainWindow)
        self.ACopy.setObjectName("ACopy")
        self.AWhoisqutrub = QtGui.QAction(MainWindow)
        self.AWhoisqutrub.setObjectName("AWhoisqutrub")
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_3 = QtGui.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtGui.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.menu.addAction(self.AExport)
        self.menu.addAction(self.action_4)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_6.menuAction())
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.AExit)
        self.menu_2.addAction(self.AFont)
        self.menu_3.addAction(self.AAbout)
        self.menu_3.addAction(self.AManual)
        self.menu_3.addAction(self.AWhoisqutrub)
        self.menu_4.addAction(self.ACopy)
        self.menu_5.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.toolBar.addAction(self.AFont)
        self.toolBar.addAction(self.ACopy)

        self.retranslateUi(MainWindow)
        self.TabVoice.setCurrentIndex(0)
        QtCore.QObject.connect(self.AExit, QtCore.SIGNAL("toggled(bool)"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "قطرب: تصريف الأفعال العربية", None, QtGui.QApplication.UnicodeUTF8))
        self.Label.setText(QtGui.QApplication.translate("MainWindow", ",", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_2.setText(QtGui.QApplication.translate("MainWindow", ",", None, QtGui.QApplication.UnicodeUTF8))
        self.TSearch.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KacstOne\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px;\">1-اكتب الكلمة التي تبحث عنها</p>\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px;\">2- اختر لغة الكلمة</p>\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px;\">3- اختر الدليل الذي تريده</p>\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px;\">4-اضغط على بحث</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.CBLanguage.setItemText(0, QtGui.QApplication.translate("MainWindow", "دليل الموارد والوسائل العامة", None, QtGui.QApplication.UnicodeUTF8))
        self.CBLexique.setItemText(0, QtGui.QApplication.translate("MainWindow", "العربية", None, QtGui.QApplication.UnicodeUTF8))
        self.CBLexique.setItemText(1, QtGui.QApplication.translate("MainWindow", "فرنسية", None, QtGui.QApplication.UnicodeUTF8))
        self.CBLexique.setItemText(2, QtGui.QApplication.translate("MainWindow", "إنجليزية", None, QtGui.QApplication.UnicodeUTF8))
        self.BConjugate.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'ae_AlMateen\'; font-size:18pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ابحث</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.BConjugate.setText(QtGui.QApplication.translate("MainWindow", "بحث", None, QtGui.QApplication.UnicodeUTF8))
        self.TabActiveResult.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "العربية", None, QtGui.QApplication.UnicodeUTF8))
        self.TabActiveResult.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "الفرنسية", None, QtGui.QApplication.UnicodeUTF8))
        self.TabActiveResult.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "الإنجليزية", None, QtGui.QApplication.UnicodeUTF8))
        self.TabVoice.setTabText(self.TabVoice.indexOf(self.TabResult), QtGui.QApplication.translate("MainWindow", "النتائج", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "ملف", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_6.setTitle(QtGui.QApplication.translate("MainWindow", "معاينة قبل الطباعة", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_2.setTitle(QtGui.QApplication.translate("MainWindow", "عرض", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_3.setTitle(QtGui.QApplication.translate("MainWindow", "مساعدة", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_4.setTitle(QtGui.QApplication.translate("MainWindow", "تحرير", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_5.setTitle(QtGui.QApplication.translate("MainWindow", "أدوات", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.AExport.setText(QtGui.QApplication.translate("MainWindow", "ت&صدير", None, QtGui.QApplication.UnicodeUTF8))
        self.AExit.setText(QtGui.QApplication.translate("MainWindow", "&خروج", None, QtGui.QApplication.UnicodeUTF8))
        self.AFont.setText(QtGui.QApplication.translate("MainWindow", "خط", None, QtGui.QApplication.UnicodeUTF8))
        self.AAbout.setText(QtGui.QApplication.translate("MainWindow", "حول البرنامج", None, QtGui.QApplication.UnicodeUTF8))
        self.AManual.setText(QtGui.QApplication.translate("MainWindow", "دليل الاستعمال", None, QtGui.QApplication.UnicodeUTF8))
        self.ACopy.setText(QtGui.QApplication.translate("MainWindow", "نسخ", None, QtGui.QApplication.UnicodeUTF8))
        self.AWhoisqutrub.setText(QtGui.QApplication.translate("MainWindow", "عن المجلس الأعلى للغة العربية", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setText(QtGui.QApplication.translate("MainWindow", "تفضيلات", None, QtGui.QApplication.UnicodeUTF8))
        self.action_3.setText(QtGui.QApplication.translate("MainWindow", "طباعة...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_4.setText(QtGui.QApplication.translate("MainWindow", "إعداد الصفحة", None, QtGui.QApplication.UnicodeUTF8))

import lexique_rc
